global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/your/slack/webhook'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'slack-notifications'
    continue: true

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring'
    send_resolved: true
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] AI採用管理システム アラート'
    text: >-
      {{ range .Alerts }}
        *アラート:* {{ .Annotations.summary }}
        *詳細:* {{ .Annotations.description }}
        *重要度:* {{ .Labels.severity }}
        *インスタンス:* {{ .Labels.instance }}
        *ステータス:* {{ .Status }}
      {{ end }}
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    username: 'Prometheus AlertManager'
    icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:white_check_mark:{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 